version: 2.1

orbs:
  architect: giantswarm/architect@6.6.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          resource_class: large
          binary: etcd-backup-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          name: push-to-registries
          context: architect
          requires:
            - go-build
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          chart: etcd-backup-operator
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          requires:
            - push-to-registries
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capa-app-collection
          context: architect
          app_name: etcd-backup-operator
          app_collection_repo: capa-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capz-app-collection
          context: architect
          app_name: etcd-backup-operator
          app_collection_repo: capz-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-proxmox-app-collection
          context: architect
          app_name: etcd-backup-operator
          app_collection_repo: proxmox-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-cloud-director-app-collection
          context: architect
          app_name: etcd-backup-operator
          app_collection_repo: cloud-director-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-vsphere-app-collection
          context: architect
          app_name: etcd-backup-operator
          app_collection_repo: vsphere-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
