version: 2.1

orbs:
  architect: giantswarm/architect@6.15.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          resource_class: large
          binary: etcd-backup-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          name: push-to-registries
          context: architect
          requires:
            - go-build
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          executor: app-build-suite
          chart: etcd-backup-operator
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          requires:
            - push-to-registries
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/
