orbs:
  architect: giantswarm/architect@4.37.0

version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - architect/go-build:
          name: go-build-etcd-backup-operator
          binary: etcd-backup-operator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build-etcd-backup-operator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-etcd-backup-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "etcd-backup-operator"
          # Make sure docker image is successfully built.
          requires:
            - push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-etcd-backup-operator-to-aws-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-etcd-backup-operator-to-azure-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-etcd-backup-operator-to-vsphere-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "etcd-backup-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-etcd-backup-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
