apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  name: {{ include "resource.default.name" . }}-exceptions
  namespace: {{ include "resource.default.namespace" . }}
spec:
  exceptions:
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces 
    - autogen-host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  - policyName: require-run-as-nonroot 
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - {{ include "resource.default.namespace" . }}
        names:
        - {{ include "resource.default.name" . }}*
