apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-operator
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  ETCDBACKUP_AWS_ACCESS_KEY: {{ .Values.Installation.V1.Secret.EtcdBackup.AWSAccessKey | b64enc | quote }}
  ETCDBACKUP_AWS_SECRET_KEY: {{ .Values.Installation.V1.Secret.EtcdBackup.AWSSecretKey | b64enc | quote }}
  ETCDBACKUP_PASSPHRASE: ""
