apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-operator
  namespace: {{ tpl .Values.resource.default.namespace  . }}
type: Opaque
data:
  ETCDBACKUP_AWS_ACCESS_KEY: {{ .Values.Installation.V1.Secret.EtcdBackup.AWSAccessKey | b64enc | quote }}
  ETCDBACKUP_AWS_SECRET_KEY: {{ .Values.Installation.V1.Secret.EtcdBackup.AWSSecretKey | b64enc | quote }}
  ETCDBACKUP_PASSPHRASE: ""
