apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  {{- if .Values.aws.irsa.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsa.roleArn }}
  {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
